# Generated by Django 6.0.6 on 2026-06-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=30, unique=True, verbose_name='Número do Protocolo')),
                ('anonimato', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3)),
                ('testemunhas', models.TextField(blank=True, null=True, verbose_name='Testemunhas')),
                ('descricao', models.TextField(verbose_name='Descrição do Ocorrido')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Denunciante')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida - Aguardando Análise'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDA', 'Concluída / Finalizada'), ('ARQUIVADA', 'Arquivada')], default='RECEBIDA', max_length=20, verbose_name='Status da Denúncia')),
                ('resposta_advogada', models.TextField(blank=True, null=True, verbose_name='Atualização / Parecer para o Denunciante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Denúncias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='denuncias/anexos/%Y/%m/%d/', verbose_name='Arquivo Anexo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denuncia', verbose_name='Denúncia')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='denuncias.denuncia')),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['criado_em'],
            },
        ),
    ]
