# Generated by Django 6.0.6 on 2026-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/chat_provas/'),
        ),
    ]
