# Generated by Django 6.0.6 on 2026-06-23 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_mensagem_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.AlterField(
            model_name='anexodenuncia',
            name='arquivo',
            field=models.FileField(upload_to='denuncias/anexos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx', 'mp4', 'wav', 'mp3', 'm4a', 'aac', 'ogg'])], verbose_name='Arquivo Anexo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/anexos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx', 'mp4', 'wav', 'mp3', 'm4a', 'aac', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
    ]
