# Generated by Django 6.0.6 on 2026-09-01 15:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('denuncias', '0003_alter_denuncia_options_alter_anexodenuncia_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorGrupo',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo de Permissão',
                'verbose_name_plural': '2. Grupos de Permissão',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='GestorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuário do Sistema',
                'verbose_name_plural': '1. Usuários do Sistema',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='anexo_visivel_denunciante',
            field=models.BooleanField(default=True, verbose_name='Deixar anexo visível para o denunciante?'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='arquivo_anexo',
            field=models.FileField(blank=True, null=True, upload_to='chat_anexos/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida - Aguardando Análise'), ('EM_ANALISE', 'Em Análise'), ('pendente_diligencia', 'Pendente de Diligência'), ('abertura_sindicancia', 'Abertura de Sindicância'), ('CONCLUIDA', 'Concluída / Finalizada'), ('ARQUIVADA', 'Arquivada')], default='RECEBIDA', max_length=20, verbose_name='Status da Denúncia'),
        ),
    ]
