# Generated by Django 6.0.6 on 2026-09-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_gestorgrupo_gestorusuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='anexo_visivel_denunciante',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='arquivo_anexo',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='visivel_denunciante',
            field=models.BooleanField(default=True, verbose_name='Visível para o Denunciante?'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem/Anotação'),
        ),
        migrations.CreateModel(
            name='AnexoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chat_anexos/')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.mensagem')),
            ],
        ),
    ]
