# Generated by Django 6.0.6 on 2026-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_remove_mensagem_anexo_visivel_denunciante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('Em Análise', 'Em Análise'), ('Determinado o processamento de sindicância interna', 'Determinado o processamento de sindicância interna'), ('Determinado o arquivamento sumário por falta de informações ou ausência de objeto passível de sindicância', 'Determinado o arquivamento sumário por falta de informações ou ausência de objeto passível de sindicância'), ('Pendente de Diligência', 'Pendente de Diligência'), ('Abertura de Sindicância', 'Abertura de Sindicância'), ('Concluída / Finalizada', 'Concluída / Finalizada'), ('Encerrada', 'Encerrada')], default='RECEBIDA', max_length=150, verbose_name='Status da Denúncia'),
        ),
    ]
