# Generated by Django 6.0.6 on 2026-09-29 12:03

import denuncias.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_alter_denuncia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexodenuncia',
            name='arquivo',
            field=models.FileField(upload_to=denuncias.models.caminho_anexos_cliente),
        ),
        migrations.AlterField(
            model_name='anexodenuncia',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denuncia'),
        ),
        migrations.AlterField(
            model_name='anexomensagem',
            name='arquivo',
            field=models.FileField(upload_to=denuncias.models.caminho_anexos_cliente),
        ),
    ]
